function data = fetch_eeg_data(dataset_id, signal_num, start_index, end_index)

str_dataset_id = sprintf('%d',dataset_id);
str_signal_num = sprintf('%d',signal_num); %channel number?
str_start_index = sprintf('%d',start_index);
str_end_index = sprintf('%d',end_index);

U = urlread('http://eegnet.clemson.edu/dev/middleware/getData.php',...
    'get',...
    {'Operation','getSignalData',...
    'DatasetID',str_dataset_id,...
    'Signal',str_signal_num,...
    'StartSeq',str_start_index,...
    'EndSeq',str_end_index,...
    'Skip','1'});

data = strread(U);

end